### ISSUE TITLE
Frozen; being attacked; becomes normal state

### ISSUE THREAD

**Issue by jamespanda** [Project-F/F.LF#1]
![2015-10-04-001515_1440x900_scrot](https://cloud.githubusercontent.com/assets/14955228/10263832/c365d622-6a2d-11e5-8a82-8f13705cbdbf.png)

**Comment by tyt2y3** [comment]
thanks for your reporting. um... can you explain the steps to reproduce?

**Comment by jamespanda** [comment]
1. David frozen
2. Freeze attack(> > J A)

**Comment by tyt2y3** [comment]
thanks for the detailed step! but I still am unable to reproduce.
I do recall that the "fall onto ground" logic has problems in some occasions, such that in fall frame (180) and y=0 it may not trigger the "fall onto ground" event. It may not be specific to freeze attacks.
thank you again for your participation. I shall think of a solution.

**Comment by tyt2y3** [comment]
I would mark this line of code as relevant [LF/character.js#L55](https://github.com/Project-F/F.LF/blob/47622964316096d5a6c8fdd8f6111d38b878c79a/LF/character.js#L55)

**Comment by olivertribe** [comment]
@tyt2y3 
I can't seem to replicate this one. Can you?

**Comment by tyt2y3** [comment]
Um... I am aware that it would occur when ps.y===0 && ps.vy===0
But how does it enter that state?
It does not happen very often.

**Comment by lyhyl** [comment]
https://user-images.githubusercontent.com/3370369/120062555-70334380-c095-11eb-82c0-af37837c4b3e.mp4

same problem?

**Comment by olivertribe** [comment]
I was able to replicate this by spamming jump and a direction whilst frozen. 
This happens with any character.

**Comment by tyt2y3** [comment]
okay so I think the key is when a character breaks out of ice and jump, he should be given an initial upward velocity.

**Comment by olivertribe** [comment]
This one has been fixed.

**Comment by tyt2y3** [comment]
Thank you everyone.
