### ISSUE TITLE
Rudolf : Clone causes game crash

### ISSUE THREAD

**Issue by olivertribe** [Project-F/F.LF#18]
Rudolf clone currently errors with 
`$.trans.next_frame_D() is undefined`

Replicate by:

1. Selecting Rudolf
2. ATK + DEF + JUMP + UP (Clone)
3. Check developer console

Rudolf Clone behavior should be:
1. Spawn 2 weaker version of Rudolf, with basic AI
2. AI should be slightly weaker than main rudolf in health but not damage (I think?)

**Comment by tyt2y3** [comment]
#26
