### ISSUE TITLE
Rudolf : Hide doesn't make Rudolf invisible

### ISSUE THREAD

**Issue by olivertribe** [Project-F/F.LF#19]
Rudolf's Hide does not make Rudolf invisible. 
This move should make Rudolf invisible to everyone.

Replicate by:

1. Selecting Rudolf
2. ATK + DEF + JUMP + DOWN (HIDE). *Smoke Animation*
3. Rudolf still visible

**Comment by bobbyng626** [comment]
I have added a few features to this skill:
1. Rudolf will be in 'super' state (not attackable) during 'invisible'
2. 'Blink' is added to shadow and the body in 2 different time according to the GC constant
3. Rudolf will not be detectable during 'invisible' time

The final outcome is as follow
![disappear_dev](https://user-images.githubusercontent.com/67236456/121338587-38a77f80-c950-11eb-82e4-bb13b4f79423.gif)


with reference with the existing published LF2 v2.0a version
![disappear](https://user-images.githubusercontent.com/67236456/121337168-d437f080-c94e-11eb-93cd-b71e20690496.gif)

**Comment by tyt2y3** [comment]
Nice work, thank you everyone!
