### ISSUE TITLE
Rudulf clone AI

### ISSUE THREAD

**Issue by tyt2y3** [Project-F/F.LF#26]
F.LF has an pluggable AI system, where AI scripts are included in content pack along with data files.
We'd want to develop a dumb AI for Rudulf clones that:

1. knows how to use projectile and D>J melee
1. would keep a far enough distance from enemy
1. would attempt to esacpe as soon as being attacked

Ref: https://github.com/Project-F/LF2_19/blob/master/AI
CHALLANGAR was written by Zort from LF Empire
CRUSHER was written by YinYin from LF Empire
both are very advanced I basically don't understand how they work!

**Comment by bobbyng626** [comment]
I am interested in working on this!

**Comment by tyt2y3** [comment]
@bobbyng626 awesome!

**Comment by bobbyng626** [comment]
https://user-images.githubusercontent.com/67236456/124260796-ad8e6380-db62-11eb-8682-9dac3b884646.mp4

**Comment by tyt2y3** [comment]
Nicely done!
