### ISSUE TITLE
Rudolf Ninja Star Bug

### ISSUE THREAD

**Issue by bobbyng626** [Project-F/F.LF#27]
Here is the current version of Multiple Ninja Star of Rudolf. As you can see there is only 1 Shuriken (ninja star) coming out from Rudolf (actually it should be 5 Shuriken placing in the same position).

![False_NinjaStar](https://user-images.githubusercontent.com/67236456/120462659-b65a1100-c3cd-11eb-9635-146685c0909d.gif)

The correct one from the Little Fighter v2.0 is also attached.

![True_NinjaStar](https://user-images.githubusercontent.com/67236456/120462715-c2de6980-c3cd-11eb-8503-940ee78646f3.gif)

**Comment by tyt2y3** [comment]
Still need to adjust the projectiles' flying distance

**Comment by bobbyng626** [comment]
Pull request completed and it had been solved

**Comment by bobbyng626** [comment]
Result of the fixed version is reflected as follow:
![correct_star](https://user-images.githubusercontent.com/67236456/121292358-68d52b00-c91c-11eb-8d97-ed601dbbdc4b.gif)

Compare with the existing published LF2 v2.0
![correct_star_LF2](https://user-images.githubusercontent.com/67236456/121292439-886c5380-c91c-11eb-9973-bcc01c914697.gif)

**Comment by tyt2y3** [comment]
Nice
