### ISSUE TITLE
Errors running F.LF on local

### ISSUE THREAD

**Issue by nykevinwong** [Project-F/F.LF#4]
Hi Project-F Developer,

I followed below guide to build and run the downloaded F.LF source code, but it's not working.  
http://www.projectf.hk/F.LF/docs/multiplayer.html

see below snapshot for the errors. the same issue occurred in both IE/Chrome.

![flf_issue](https://user-images.githubusercontent.com/6019725/35478029-9cb0db94-03a0-11e8-81fb-f5b27fb8fa29.png)

**Comment by tyt2y3** [comment]
To troubleshoot this issue, you can divide it into two parts
1) is the locally hosted F.LF running fine? (localhost:8000)
2) is the PvP running fine?

To test 1) you can use your local version and connect to the public [F.LF Lobby](http://f-lobby.herokuapp.com/)
To test 2) you use the online [F.LF](http://www.projectf.hk/F.LF/game/game.html) to connect to your local server (localhost:8001)

**Comment by nykevinwong** [comment]
Hi tyt2y3,

According to the guide of running F.LF(http://www.projectf.hk/F.LF/docs/multiplayer.html), 
I shall be able  to start F.LF from your local web server and Click network game. In the server list, selects third party server. Enter http://localhost:8001 (or whatever port F.Lobby is listening). Click Connect.

However, there're no such options listed when running the local web servers. 
see the attached snapshot, you can see the local web sever running, but no network game option, not sever list is displayed.

![lf2_q1](https://user-images.githubusercontent.com/6019725/37625669-41d48812-2ba3-11e8-9941-b9fee126bd0f.png)

**Comment by nykevinwong** [comment]
Regarding F.LF bundled python web server, can you provide the instruction of how to start it ? I have never program in Python; please guide me through it.

**Comment by nykevinwong** [comment]
Hi tyt2y3,
below are my attempts of running LF2 bundled web server. Unfortunately, I am unable to run it.

![lf2_static_server](https://user-images.githubusercontent.com/6019725/37721284-7cb4a1d0-2cff-11e8-8622-6a1aa33c76f6.png)

**Comment by nykevinwong** [comment]
hi tyt2y3,

I am really curious and really interested in making a game like LF2. I am a fan of LF2 as well.
if you can spend some time to update README or provide a video of how to set this github project up, I can work on porting all this code into haxeflixel once I go over and learn all these source code and even learn python if necessary. I can help to fix issues from this github repository as well. I'd like to make a new game like LF2 and bring LF2 style games back to LF2 fans.

below is my qualification of doing this:
I am a ASP.NET MVC web developer for my full time job. In my spare time, I also worked on my android game project using HaxeFlixel => (https://play.google.com/store/apps/details?id=com.gamecopter.supermario.mario.gaiaisland).

**Comment by nykevinwong** [comment]
hi tyt2y3,
I am able to run this project on my local via below step. 
1. run the command: "git clone https://github.com/Project-F/F.LF"
2. inside local F.LF folder, run the command "git clone https://github.com/Project-F/LF2_19", this will create LF2_19 on local for the required game asset.
3. start a command prompt, and run a http web server under a local F.LF folder. I use nodeJs's http-server for this. in my case, this http server rans on 8080 port.
4.  inside local F.LF folder, run the command "python -m SimpleHTTPServer"
5.  go to http://localhost:8080/ 
![lf2_success](https://user-images.githubusercontent.com/6019725/37745673-77a48bfe-2d4c-11e8-9a04-f2b7f9025640.png)

**Comment by nykevinwong** [comment]
yes. I am able to run local multiplayer feature.

**Comment by nykevinwong** [comment]
hi tyt2ys,

I'd like to study the whole source code, but I'd like to study simpler version of source code first to speed up learning process.
I know the current F.LF is v0.9.
Is there a minimum bare bone of the source code I can study to begin with?
are there any runnable or working F.LF 2 that is v0.1 or v0.2?
for example, is there a very simple demo source code that only contain L.F. fighters able to fight each other , via keyboard, without menu, UI, and even AI?

**Comment by nykevinwong** [comment]
updated readme. please review the pull request => https://github.com/Project-F/F.LF/pull/5

**Comment by lordelan** [comment]
Sorry to use this issue but as there's no forum or anything I just wanted to take the chance here to say THANK YOU for doing an open source lf2. It's what I always wished for.
This should run great on the Nintendo Switch! :)

**Comment by tyt2y3** [comment]
@lordelan thank you a lot for your thankful comment. Go spread the world about it so that this legacy will not lost. :)
