### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Trilarion** [Project-F/F.LF#7]
There seems to be no license information included in the repository or I cannot find it. What is the license of the code and the artwork? I understand the code is a clean room remake effort, but it could still have different licenses like GPL, MIT, BSD,.. or others. Is the artwork taken from LF2 (with permission)?

**Comment by tyt2y3** [comment]
Deliberately, this repository is an implementation of the game engine and does not contain any copyrighted material from original LF2.
The license was written [here](http://project-f.github.io/license.html).
However as a game it cannot function without a content pack (artwork & datafiles), which is [LF2_19](https://github.com/Project-F/LF2_19).
If we can create a community content pack independently, then this project can be a free software in the open source sense.

**Comment by Trilarion** [comment]
Thanks for the reply. Maybe the license information could also be added to the repository.

Instead of replacing the content completely, one could maybe also contact the original developers and ask them if they can license the original content also under the CC license.

**Comment by tyt2y3** [comment]
License added f2edcb7a755154d1c9ed0cfa01624148553f0ad0
