### ISSUE TITLE
arrows and shurikans not falling onto ground

### ISSUE THREAD

**Issue by DaKnig** [Project-F/F.LF#9]
![shurikans_go_brrr](https://user-images.githubusercontent.com/37626476/100469934-e7d0e780-30df-11eb-9372-9d40b9b17aef.png)
as we can see the shurikans go up, not down.
same for Henry's arrows.

steps to reproduce: play against Rudlof, let him throw a few, see anti gravity in action.

**Comment by tyt2y3** [comment]
Thank you for your interest. I am sorry, I guess Henry and Rudolf is WIP, and I accidentally pushed these two characters to release. May be I should hide them for now?

**Comment by DaKnig** [comment]
I am not a web dev so I am not sure I can help with the code, but it should be as easy as substracting the vertical speed from the vertical position, not adding them

also the arrows , when you fire them from an airborne position they travel on the ground indefinitely- they should be a different entity from the normal arrows and should break when they hit the ground. 

anyways I dont think hiding that is a good idea. should work on it for sure though :)

**Comment by olivertribe** [comment]
Issue fixed in PR #16

**Comment by tyt2y3** [comment]
Nice. Thank you so much for all!
